// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: version.proto

package edgeproto

import (
	"encoding/json"
	fmt "fmt"
	"github.com/edgexr/edge-cloud-platform/pkg/util"
	_ "github.com/edgexr/edge-cloud-platform/tools/protogen"
	_ "github.com/gogo/protobuf/gogoproto"
	proto "github.com/gogo/protobuf/proto"
	math "math"
	reflect "reflect"
	"strconv"
	strings "strings"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

// Below enum lists hashes as well as corresponding versions
type VersionHash int32

const (
	VersionHash_HASH_d41d8cd98f00b204e9800998ecf8427e VersionHash = 0
	//interim versions deleted
	VersionHash_HASH_c2d882033b0c14f28cece41cf4010060 VersionHash = 52
	VersionHash_HASH_14ae4c721c1bace6e8379d0061a72a77 VersionHash = 53
	VersionHash_HASH_eff9d3a6c74fd02840efce05d1984e8d VersionHash = 54
	VersionHash_HASH_eac56710c013d954db31eeb306b514a4 VersionHash = 55
	VersionHash_HASH_75883d14000640b2ecf694fe8ef9192b VersionHash = 56
)

var VersionHash_name = map[int32]string{
	0:  "HASH_d41d8cd98f00b204e9800998ecf8427e",
	52: "HASH_c2d882033b0c14f28cece41cf4010060",
	53: "HASH_14ae4c721c1bace6e8379d0061a72a77",
	54: "HASH_eff9d3a6c74fd02840efce05d1984e8d",
	55: "HASH_eac56710c013d954db31eeb306b514a4",
	56: "HASH_75883d14000640b2ecf694fe8ef9192b",
}

var VersionHash_value = map[string]int32{
	"HASH_d41d8cd98f00b204e9800998ecf8427e": 0,
	"HASH_c2d882033b0c14f28cece41cf4010060": 52,
	"HASH_14ae4c721c1bace6e8379d0061a72a77": 53,
	"HASH_eff9d3a6c74fd02840efce05d1984e8d": 54,
	"HASH_eac56710c013d954db31eeb306b514a4": 55,
	"HASH_75883d14000640b2ecf694fe8ef9192b": 56,
}

func (x VersionHash) String() string {
	return proto.EnumName(VersionHash_name, int32(x))
}

func (VersionHash) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_7d2c07d79758f814, []int{0}
}

func init() {
	proto.RegisterEnum("edgeproto.VersionHash", VersionHash_name, VersionHash_value)
}

func init() { proto.RegisterFile("version.proto", fileDescriptor_7d2c07d79758f814) }

var fileDescriptor_7d2c07d79758f814 = []byte{
	// 410 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x3c, 0x91, 0x31, 0x8b, 0xd4, 0x40,
	0x14, 0x80, 0x13, 0x0b, 0xe1, 0xf6, 0x38, 0x8c, 0xe1, 0x8a, 0x10, 0xce, 0x60, 0x63, 0xa1, 0x85,
	0xf7, 0x66, 0x32, 0xc9, 0xcc, 0x88, 0x20, 0xa7, 0x78, 0xac, 0x1c, 0x28, 0xb8, 0x68, 0x61, 0x23,
	0x33, 0xf3, 0xde, 0xc4, 0x05, 0x2f, 0xb3, 0x26, 0x51, 0xb0, 0xb5, 0xdc, 0xca, 0x9f, 0x75, 0xe5,
	0x95, 0x96, 0xba, 0xfb, 0x17, 0x8c, 0x58, 0x8a, 0xbb, 0x7b, 0xd7, 0x7d, 0xef, 0xf1, 0xbd, 0xaf,
	0x79, 0x93, 0x83, 0x2f, 0xd4, 0xf5, 0xf3, 0xd0, 0x3e, 0x5c, 0x74, 0x61, 0x08, 0xe9, 0x1e, 0x61,
	0x43, 0x1b, 0xcc, 0xef, 0x0c, 0x21, 0x7c, 0xec, 0x8f, 0x37, 0x43, 0x43, 0xed, 0x35, 0x6c, 0xcd,
	0xfc, 0xb0, 0x09, 0x4d, 0xd8, 0xe0, 0xf1, 0x7f, 0xda, 0x6e, 0x1f, 0xfc, 0xb9, 0x31, 0xd9, 0x7f,
	0xbb, 0x2d, 0x4e, 0x4d, 0xff, 0x21, 0xbd, 0x3f, 0xb9, 0x37, 0x3d, 0x99, 0x4d, 0xdf, 0xa3, 0x60,
	0xa8, 0x1c, 0x6a, 0xe5, 0x01, 0x2c, 0x07, 0x41, 0x5a, 0x01, 0x68, 0xad, 0xc8, 0x79, 0x25, 0xb8,
	0xa4, 0x24, 0xba, 0x56, 0x1d, 0x47, 0xa5, 0x38, 0x94, 0xa5, 0x05, 0xc7, 0x84, 0xe7, 0xca, 0x91,
	0x23, 0xc1, 0x9c, 0x17, 0xc0, 0x00, 0x6a, 0x48, 0x44, 0xfa, 0x64, 0xa7, 0x32, 0x61, 0x48, 0x38,
	0xc9, 0x99, 0x63, 0xd6, 0x38, 0xaa, 0x49, 0x95, 0x52, 0x23, 0x40, 0xcd, 0x8c, 0xe4, 0x46, 0xca,
	0xa4, 0xca, 0x0f, 0x97, 0x63, 0x96, 0xbc, 0x59, 0x34, 0x9d, 0x41, 0x7a, 0xd6, 0x9d, 0xbf, 0x6a,
	0x9f, 0x63, 0x43, 0xe9, 0xe3, 0x5d, 0x80, 0xbc, 0xd7, 0x58, 0x9a, 0xda, 0x49, 0xe1, 0x11, 0xb8,
	0x12, 0x40, 0xde, 0x11, 0x54, 0xc8, 0xb4, 0x12, 0xa4, 0x30, 0xa9, 0xf3, 0xdb, 0xcb, 0x31, 0x3b,
	0x38, 0x41, 0x9c, 0x0d, 0x66, 0x98, 0xbb, 0xd3, 0x4f, 0xd8, 0xa6, 0x67, 0x57, 0xd7, 0xc6, 0x55,
	0xb5, 0x64, 0xe0, 0x80, 0x95, 0xa8, 0x2b, 0x81, 0xb6, 0x64, 0x44, 0xb6, 0x84, 0xda, 0x56, 0x4c,
	0x18, 0x91, 0xc8, 0xfc, 0xee, 0x72, 0xcc, 0x8e, 0x5e, 0xb4, 0xfd, 0x60, 0x5a, 0x47, 0x67, 0xf4,
	0xb5, 0x7f, 0x4d, 0xcd, 0x3c, 0xb4, 0x33, 0x17, 0x16, 0x84, 0x2f, 0xcd, 0x39, 0xa5, 0x8f, 0x76,
	0x31, 0x59, 0x29, 0x55, 0x22, 0x13, 0x00, 0x50, 0x0b, 0xb0, 0x9c, 0x9c, 0xaf, 0xb5, 0xf0, 0xa4,
	0xc8, 0x6b, 0xa6, 0xb9, 0x4d, 0x54, 0x7e, 0x6b, 0x39, 0x66, 0xfb, 0xef, 0x42, 0x4b, 0xa7, 0x64,
	0x86, 0xcf, 0x1d, 0xe5, 0x7b, 0x7f, 0x7f, 0x67, 0xf1, 0xb7, 0x31, 0x8b, 0xe1, 0xe9, 0xd1, 0xc5,
	0xaf, 0x22, 0xba, 0x58, 0x15, 0xf1, 0xe5, 0xaa, 0x88, 0x7f, 0xae, 0x8a, 0xf8, 0xfb, 0xba, 0x88,
	0x2e, 0xd7, 0x45, 0xf4, 0x63, 0x5d, 0x44, 0xf6, 0xe6, 0xe6, 0x3b, 0xe5, 0xbf, 0x00, 0x00, 0x00,
	0xff, 0xff, 0x39, 0xe0, 0x91, 0x9a, 0xee, 0x01, 0x00, 0x00,
}
var VersionHashStrings = []string{
	"HASH_d41d8cd98f00b204e9800998ecf8427e",
	"HASH_c2d882033b0c14f28cece41cf4010060",
	"HASH_14ae4c721c1bace6e8379d0061a72a77",
	"HASH_eff9d3a6c74fd02840efce05d1984e8d",
	"HASH_eac56710c013d954db31eeb306b514a4",
	"HASH_75883d14000640b2ecf694fe8ef9192b",
}

const (
	VersionHashHASHD41D8Cd98F00B204E9800998Ecf8427E  uint64 = 1 << 0
	VersionHashHASHC2D882033B0C14F28Cece41Cf4010060  uint64 = 1 << 1
	VersionHashHASH_14Ae4C721C1Bace6E8379D0061A72A77 uint64 = 1 << 2
	VersionHashHASHEff9D3A6C74Fd02840Efce05D1984E8D  uint64 = 1 << 3
	VersionHashHASHEac56710C013D954Db31Eeb306B514A4  uint64 = 1 << 4
	VersionHashHASH_75883D14000640B2Ecf694Fe8Ef9192B uint64 = 1 << 5
)

var VersionHash_CamelName = map[int32]string{
	// HASH_d41d8cd98f00b204e9800998ecf8427e -> HashD41D8Cd98F00B204E9800998Ecf8427E
	0: "HashD41D8Cd98F00B204E9800998Ecf8427E",
	// HASH_c2d882033b0c14f28cece41cf4010060 -> HashC2D882033B0C14F28Cece41Cf4010060
	52: "HashC2D882033B0C14F28Cece41Cf4010060",
	// HASH_14ae4c721c1bace6e8379d0061a72a77 -> Hash14Ae4C721C1Bace6E8379D0061A72A77
	53: "Hash14Ae4C721C1Bace6E8379D0061A72A77",
	// HASH_eff9d3a6c74fd02840efce05d1984e8d -> HashEff9D3A6C74Fd02840Efce05D1984E8D
	54: "HashEff9D3A6C74Fd02840Efce05D1984E8D",
	// HASH_eac56710c013d954db31eeb306b514a4 -> HashEac56710C013D954Db31Eeb306B514A4
	55: "HashEac56710C013D954Db31Eeb306B514A4",
	// HASH_75883d14000640b2ecf694fe8ef9192b -> Hash75883D14000640B2Ecf694Fe8Ef9192B
	56: "Hash75883D14000640B2Ecf694Fe8Ef9192B",
}
var VersionHash_CamelValue = map[string]int32{
	"HashD41D8Cd98F00B204E9800998Ecf8427E": 0,
	"HashC2D882033B0C14F28Cece41Cf4010060": 52,
	"Hash14Ae4C721C1Bace6E8379D0061A72A77": 53,
	"HashEff9D3A6C74Fd02840Efce05D1984E8D": 54,
	"HashEac56710C013D954Db31Eeb306B514A4": 55,
	"Hash75883D14000640B2Ecf694Fe8Ef9192B": 56,
}

func ParseVersionHash(data interface{}) (VersionHash, error) {
	if val, ok := data.(VersionHash); ok {
		return val, nil
	} else if str, ok := data.(string); ok {
		val, ok := VersionHash_CamelValue[util.CamelCase(str)]
		if !ok {
			// may have omitted common prefix
			val, ok = VersionHash_CamelValue["Hash"+util.CamelCase(str)]
		}
		if !ok {
			// may be int value instead of enum name
			ival, err := strconv.Atoi(str)
			val = int32(ival)
			if err == nil {
				_, ok = VersionHash_CamelName[val]
			}
		}
		if !ok {
			return VersionHash(0), fmt.Errorf("Invalid VersionHash value %q", str)
		}
		return VersionHash(val), nil
	} else if ival, ok := data.(int32); ok {
		if _, ok := VersionHash_CamelName[ival]; ok {
			return VersionHash(ival), nil
		} else {
			return VersionHash(0), fmt.Errorf("Invalid VersionHash value %d", ival)
		}
	}
	return VersionHash(0), fmt.Errorf("Invalid VersionHash value %v", data)
}

func (e *VersionHash) UnmarshalYAML(unmarshal func(interface{}) error) error {
	var str string
	err := unmarshal(&str)
	if err != nil {
		return err
	}
	val, err := ParseVersionHash(str)
	if err != nil {
		return err
	}
	*e = val
	return nil
}

func (e VersionHash) MarshalYAML() (interface{}, error) {
	str := proto.EnumName(VersionHash_CamelName, int32(e))
	str = strings.TrimPrefix(str, "Hash")
	return str, nil
}

// custom JSON encoding/decoding
func (e *VersionHash) UnmarshalJSON(b []byte) error {
	var str string
	err := json.Unmarshal(b, &str)
	if err == nil {
		val, err := ParseVersionHash(str)
		if err != nil {
			return &json.UnmarshalTypeError{
				Value: "string " + str,
				Type:  reflect.TypeOf(VersionHash(0)),
			}
		}
		*e = VersionHash(val)
		return nil
	}
	var ival int32
	err = json.Unmarshal(b, &ival)
	if err == nil {
		val, err := ParseVersionHash(ival)
		if err == nil {
			*e = val
			return nil
		}
	}
	return &json.UnmarshalTypeError{
		Value: "value " + string(b),
		Type:  reflect.TypeOf(VersionHash(0)),
	}
}

func (e VersionHash) MarshalJSON() ([]byte, error) {
	str := proto.EnumName(VersionHash_CamelName, int32(e))
	str = strings.TrimPrefix(str, "Hash")
	return json.Marshal(str)
}

var VersionHashCommonPrefix = "Hash"

// Keys being hashed:
// AlertPolicyKey
// AppInstKey
// AppInstKeyV1
// AppInstKeyV2
// AppKey
// CloudletKey
// CloudletNodeKey
// ClusterInstKeyV1
// ClusterInstKeyV2
// ClusterKey
// ClusterKeyV1
// ControllerKey
// DeviceKey
// FedAppInstKey
// FlavorKey
// FlowRateLimitSettingsKey
// GPUDriverKey
// MaxReqsRateLimitSettingsKey
// NetworkKey
// NodeKey
// PolicyKey
// RateLimitSettingsKey
// ResTagTableKey
// TPEInstanceKey
// TrustPolicyExceptionKey
// VMPoolKey
// VirtualClusterInstKeyV1
// ZoneKey
// ZonePoolKey

type DataModelVersion struct {
	Hash string
	ID   int32
}

func GetDataModelVersion() *DataModelVersion {
	return &DataModelVersion{
		Hash: "75883d14000640b2ecf694fe8ef9192b",
		ID:   56,
	}
}
