// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: trustpolicy.proto

package testutil

import (
	"context"
	fmt "fmt"
	edgeproto "github.com/edgexr/edge-cloud-platform/api/edgeproto"
	"github.com/edgexr/edge-cloud-platform/pkg/cli"
	"github.com/edgexr/edge-cloud-platform/pkg/edgectl/wrapper"
	"github.com/edgexr/edge-cloud-platform/pkg/log"
	_ "github.com/edgexr/edge-cloud-platform/tools/protogen"
	_ "github.com/gogo/googleapis/google/api"
	_ "github.com/gogo/protobuf/gogoproto"
	proto "github.com/gogo/protobuf/proto"
	"github.com/stretchr/testify/require"
	"google.golang.org/grpc"
	"io"
	math "math"
	"testing"
	"time"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// Auto-generated code: DO NOT EDIT

type ShowTrustPolicy struct {
	Data map[string]edgeproto.TrustPolicy
	grpc.ServerStream
	Ctx context.Context
}

func (x *ShowTrustPolicy) Init() {
	x.Data = make(map[string]edgeproto.TrustPolicy)
}

func (x *ShowTrustPolicy) Send(m *edgeproto.TrustPolicy) error {
	x.Data[m.GetKey().GetKeyString()] = *m
	return nil
}

func (x *ShowTrustPolicy) Context() context.Context {
	return x.Ctx
}

var TrustPolicyShowExtraCount = 0

type CudStreamoutTrustPolicy struct {
	grpc.ServerStream
	Ctx context.Context
}

func (x *CudStreamoutTrustPolicy) Send(res *edgeproto.Result) error {
	fmt.Println(res)
	return nil
}

func (x *CudStreamoutTrustPolicy) Context() context.Context {
	return x.Ctx
}

func NewCudStreamoutTrustPolicy(ctx context.Context) *CudStreamoutTrustPolicy {
	return &CudStreamoutTrustPolicy{
		Ctx: ctx,
	}
}

func TrustPolicyReadResultStream(stream ResultStream, err error) error {
	if err != nil {
		return err
	}
	for {
		res, err := stream.Recv()
		if err == io.EOF {
			return nil
		}
		if err != nil {
			return err
		}
		fmt.Println(res)
	}
}

func (x *ShowTrustPolicy) ReadStream(stream edgeproto.TrustPolicyApi_ShowTrustPolicyClient, err error) {
	x.Data = make(map[string]edgeproto.TrustPolicy)
	if err != nil {
		return
	}
	for {
		obj, err := stream.Recv()
		if err == io.EOF {
			break
		}
		if err != nil {
			break
		}
		x.Data[obj.GetKey().GetKeyString()] = *obj
	}
}

func (x *ShowTrustPolicy) CheckFound(obj *edgeproto.TrustPolicy) bool {
	_, found := x.Data[obj.GetKey().GetKeyString()]
	return found
}

func (x *ShowTrustPolicy) AssertFound(t *testing.T, obj *edgeproto.TrustPolicy) {
	check, found := x.Data[obj.GetKey().GetKeyString()]
	require.True(t, found, "find TrustPolicy %s", obj.GetKey().GetKeyString())
	if found && !check.Matches(obj, edgeproto.MatchIgnoreBackend(), edgeproto.MatchSortArrayedKeys()) {
		require.Equal(t, *obj, check, "TrustPolicy are equal")
	}
	if found {
		// remove in case there are dups in the list, so the
		// same object cannot be used again
		delete(x.Data, obj.GetKey().GetKeyString())
	}
}

func (x *ShowTrustPolicy) AssertNotFound(t *testing.T, obj *edgeproto.TrustPolicy) {
	_, found := x.Data[obj.GetKey().GetKeyString()]
	require.False(t, found, "do not find TrustPolicy %s", obj.GetKey().GetKeyString())
}

func WaitAssertFoundTrustPolicy(t *testing.T, api edgeproto.TrustPolicyApiClient, obj *edgeproto.TrustPolicy, count int, retry time.Duration) {
	show := ShowTrustPolicy{}
	for ii := 0; ii < count; ii++ {
		ctx, cancel := context.WithTimeout(context.Background(), retry)
		stream, err := api.ShowTrustPolicy(ctx, obj)
		show.ReadStream(stream, err)
		cancel()
		if show.CheckFound(obj) {
			break
		}
		time.Sleep(retry)
	}
	show.AssertFound(t, obj)
}

func WaitAssertNotFoundTrustPolicy(t *testing.T, api edgeproto.TrustPolicyApiClient, obj *edgeproto.TrustPolicy, count int, retry time.Duration) {
	show := ShowTrustPolicy{}
	filterNone := edgeproto.TrustPolicy{}
	for ii := 0; ii < count; ii++ {
		ctx, cancel := context.WithTimeout(context.Background(), retry)
		stream, err := api.ShowTrustPolicy(ctx, &filterNone)
		show.ReadStream(stream, err)
		cancel()
		if !show.CheckFound(obj) {
			break
		}
		time.Sleep(retry)
	}
	show.AssertNotFound(t, obj)
}

// Wrap the api with a common interface
type TrustPolicyCommonApi struct {
	internal_api edgeproto.TrustPolicyApiServer
	client_api   edgeproto.TrustPolicyApiClient
}

func (x *TrustPolicyCommonApi) CreateTrustPolicy(ctx context.Context, in *edgeproto.TrustPolicy) (*edgeproto.Result, error) {
	copy := &edgeproto.TrustPolicy{}
	*copy = *in
	if x.internal_api != nil {
		err := x.internal_api.CreateTrustPolicy(copy, NewCudStreamoutTrustPolicy(ctx))
		return &edgeproto.Result{}, err
	} else {
		stream, err := x.client_api.CreateTrustPolicy(ctx, copy)
		err = TrustPolicyReadResultStream(stream, err)
		return &edgeproto.Result{}, unwrapGrpcError(err)
	}
}

func (x *TrustPolicyCommonApi) DeleteTrustPolicy(ctx context.Context, in *edgeproto.TrustPolicy) (*edgeproto.Result, error) {
	copy := &edgeproto.TrustPolicy{}
	*copy = *in
	if x.internal_api != nil {
		err := x.internal_api.DeleteTrustPolicy(copy, NewCudStreamoutTrustPolicy(ctx))
		return &edgeproto.Result{}, err
	} else {
		stream, err := x.client_api.DeleteTrustPolicy(ctx, copy)
		err = TrustPolicyReadResultStream(stream, err)
		return &edgeproto.Result{}, unwrapGrpcError(err)
	}
}

func (x *TrustPolicyCommonApi) UpdateTrustPolicy(ctx context.Context, in *edgeproto.TrustPolicy) (*edgeproto.Result, error) {
	copy := &edgeproto.TrustPolicy{}
	*copy = *in
	if x.internal_api != nil {
		err := x.internal_api.UpdateTrustPolicy(copy, NewCudStreamoutTrustPolicy(ctx))
		return &edgeproto.Result{}, err
	} else {
		stream, err := x.client_api.UpdateTrustPolicy(ctx, copy)
		err = TrustPolicyReadResultStream(stream, err)
		return &edgeproto.Result{}, unwrapGrpcError(err)
	}
}

func (x *TrustPolicyCommonApi) ShowTrustPolicy(ctx context.Context, filter *edgeproto.TrustPolicy, showData *ShowTrustPolicy) error {
	if x.internal_api != nil {
		showData.Ctx = ctx
		return x.internal_api.ShowTrustPolicy(filter, showData)
	} else {
		stream, err := x.client_api.ShowTrustPolicy(ctx, filter)
		showData.ReadStream(stream, err)
		return unwrapGrpcError(err)
	}
}

func NewInternalTrustPolicyApi(api edgeproto.TrustPolicyApiServer) *TrustPolicyCommonApi {
	apiWrap := TrustPolicyCommonApi{}
	apiWrap.internal_api = api
	return &apiWrap
}

func NewClientTrustPolicyApi(api edgeproto.TrustPolicyApiClient) *TrustPolicyCommonApi {
	apiWrap := TrustPolicyCommonApi{}
	apiWrap.client_api = api
	return &apiWrap
}

type TrustPolicyTestOptions struct {
	createdData []edgeproto.TrustPolicy
}

type TrustPolicyTestOp func(opts *TrustPolicyTestOptions)

func WithCreatedTrustPolicyTestData(createdData []edgeproto.TrustPolicy) TrustPolicyTestOp {
	return func(opts *TrustPolicyTestOptions) { opts.createdData = createdData }
}

func InternalTrustPolicyTest(t *testing.T, test string, api edgeproto.TrustPolicyApiServer, testData []edgeproto.TrustPolicy, ops ...TrustPolicyTestOp) {
	span := log.StartSpan(log.DebugLevelApi, "InternalTrustPolicyTest")
	defer span.Finish()
	ctx := log.ContextWithSpan(context.Background(), span)

	switch test {
	case "cud":
		basicTrustPolicyCudTest(t, ctx, NewInternalTrustPolicyApi(api), testData, ops...)
	case "show":
		basicTrustPolicyShowTest(t, ctx, NewInternalTrustPolicyApi(api), testData)
	}
}

func ClientTrustPolicyTest(t *testing.T, test string, api edgeproto.TrustPolicyApiClient, testData []edgeproto.TrustPolicy, ops ...TrustPolicyTestOp) {
	span := log.StartSpan(log.DebugLevelApi, "ClientTrustPolicyTest")
	defer span.Finish()
	ctx := log.ContextWithSpan(context.Background(), span)

	switch test {
	case "cud":
		basicTrustPolicyCudTest(t, ctx, NewClientTrustPolicyApi(api), testData, ops...)
	case "show":
		basicTrustPolicyShowTest(t, ctx, NewClientTrustPolicyApi(api), testData)
	}
}

func basicTrustPolicyShowTest(t *testing.T, ctx context.Context, api *TrustPolicyCommonApi, testData []edgeproto.TrustPolicy) {
	var err error

	show := ShowTrustPolicy{}
	show.Init()
	filterNone := edgeproto.TrustPolicy{}
	err = api.ShowTrustPolicy(ctx, &filterNone, &show)
	require.Nil(t, err, "show data")
	require.Equal(t, len(testData)+TrustPolicyShowExtraCount, len(show.Data), "Show count")
	for _, obj := range testData {
		show.AssertFound(t, &obj)
	}
}

func GetTrustPolicy(t *testing.T, ctx context.Context, api *TrustPolicyCommonApi, key *edgeproto.PolicyKey, out *edgeproto.TrustPolicy) bool {
	var err error

	show := ShowTrustPolicy{}
	show.Init()
	filter := edgeproto.TrustPolicy{}
	filter.SetKey(key)
	err = api.ShowTrustPolicy(ctx, &filter, &show)
	require.Nil(t, err, "show data")
	obj, found := show.Data[key.GetKeyString()]
	if found {
		*out = obj
	}
	return found
}

func basicTrustPolicyCudTest(t *testing.T, ctx context.Context, api *TrustPolicyCommonApi, testData []edgeproto.TrustPolicy, ops ...TrustPolicyTestOp) {
	var err error

	if len(testData) < 3 {
		require.True(t, false, "Need at least 3 test data objects")
		return
	}
	options := TrustPolicyTestOptions{}
	for _, op := range ops {
		op(&options)
	}
	createdData := testData
	if options.createdData != nil {
		createdData = options.createdData
	}

	// test create
	CreateTrustPolicyData(t, ctx, api, testData)

	// test duplicate Create - should fail
	_, err = api.CreateTrustPolicy(ctx, &testData[0])
	require.NotNil(t, err, "Create duplicate TrustPolicy")

	// test show all items
	basicTrustPolicyShowTest(t, ctx, api, createdData)

	// test Delete
	_, err = api.DeleteTrustPolicy(ctx, &createdData[0])
	require.Nil(t, err, "Delete TrustPolicy %s", testData[0].GetKey().GetKeyString())
	show := ShowTrustPolicy{}
	show.Init()
	filterNone := edgeproto.TrustPolicy{}
	err = api.ShowTrustPolicy(ctx, &filterNone, &show)
	require.Nil(t, err, "show data")
	require.Equal(t, len(createdData)-1+TrustPolicyShowExtraCount, len(show.Data), "Show count")
	show.AssertNotFound(t, &createdData[0])
	// test update of missing object
	_, err = api.UpdateTrustPolicy(ctx, &createdData[0])
	require.NotNil(t, err, "Update missing object")
	// Create it back
	_, err = api.CreateTrustPolicy(ctx, &testData[0])
	require.Nil(t, err, "Create TrustPolicy %s", testData[0].GetKey().GetKeyString())

	// test invalid keys
	bad := edgeproto.TrustPolicy{}
	_, err = api.CreateTrustPolicy(ctx, &bad)
	require.NotNil(t, err, "Create TrustPolicy with no key info")

}

func InternalTrustPolicyCreate(t *testing.T, api edgeproto.TrustPolicyApiServer, testData []edgeproto.TrustPolicy) {
	span := log.StartSpan(log.DebugLevelApi, "InternalTrustPolicyCreate")
	defer span.Finish()
	ctx := log.ContextWithSpan(context.Background(), span)

	CreateTrustPolicyData(t, ctx, NewInternalTrustPolicyApi(api), testData)
}

func ClientTrustPolicyCreate(t *testing.T, api edgeproto.TrustPolicyApiClient, testData []edgeproto.TrustPolicy) {
	span := log.StartSpan(log.DebugLevelApi, "ClientTrustPolicyCreate")
	defer span.Finish()
	ctx := log.ContextWithSpan(context.Background(), span)

	CreateTrustPolicyData(t, ctx, NewClientTrustPolicyApi(api), testData)
}

func CreateTrustPolicyData(t *testing.T, ctx context.Context, api *TrustPolicyCommonApi, testData []edgeproto.TrustPolicy) {
	var err error

	for ii := range testData {
		obj := testData[ii]
		_, err = api.CreateTrustPolicy(ctx, &obj)
		require.Nil(t, err, "Create TrustPolicy %s", obj.GetKey().GetKeyString())
	}
}

func InternalTrustPolicyDelete(t *testing.T, api edgeproto.TrustPolicyApiServer, testData []edgeproto.TrustPolicy) {
	span := log.StartSpan(log.DebugLevelApi, "InternalTrustPolicyDelete")
	defer span.Finish()
	ctx := log.ContextWithSpan(context.Background(), span)

	DeleteTrustPolicyData(t, ctx, NewInternalTrustPolicyApi(api), testData)
}

func InternalTrustPolicyDeleteAll(t *testing.T, ctx context.Context, api edgeproto.TrustPolicyApiServer, data []edgeproto.TrustPolicy) {
	intapi := NewInternalTrustPolicyApi(api)
	log.SpanLog(ctx, log.DebugLevelInfo, "deleting all TrustPolicys", "count", len(data))
	DeleteTrustPolicyData(t, ctx, intapi, data)
}

func ClientTrustPolicyDelete(t *testing.T, api edgeproto.TrustPolicyApiClient, testData []edgeproto.TrustPolicy) {
	span := log.StartSpan(log.DebugLevelApi, "ClientTrustPolicyDelete")
	defer span.Finish()
	ctx := log.ContextWithSpan(context.Background(), span)

	DeleteTrustPolicyData(t, ctx, NewClientTrustPolicyApi(api), testData)
}

func DeleteTrustPolicyData(t *testing.T, ctx context.Context, api *TrustPolicyCommonApi, testData []edgeproto.TrustPolicy) {
	var err error

	for ii := range testData {
		obj := testData[ii]
		_, err = api.DeleteTrustPolicy(ctx, &obj)
		require.Nil(t, err, "Delete TrustPolicy %s", obj.GetKey().GetKeyString())
	}
}

func FindTrustPolicyData(key *edgeproto.PolicyKey, testData []edgeproto.TrustPolicy) (*edgeproto.TrustPolicy, bool) {
	for ii, _ := range testData {
		if testData[ii].GetKey().Matches(key) {
			return &testData[ii], true
		}
	}
	return nil, false
}

func (r *Run) TrustPolicyApi(data *[]edgeproto.TrustPolicy, dataMap interface{}, dataOut interface{}) {
	log.DebugLog(log.DebugLevelApi, "API for TrustPolicy", "mode", r.Mode)
	if r.Mode == "show" {
		obj := &edgeproto.TrustPolicy{}
		out, err := r.client.ShowTrustPolicy(r.ctx, obj)
		if err != nil {
			r.logErr("TrustPolicyApi", err)
		} else {
			outp, ok := dataOut.(*[]edgeproto.TrustPolicy)
			if !ok {
				panic(fmt.Sprintf("RunTrustPolicyApi expected dataOut type *[]edgeproto.TrustPolicy, but was %T", dataOut))
			}
			*outp = append(*outp, out...)
		}
		return
	}
	for ii, objD := range *data {
		obj := &objD
		switch r.Mode {
		case "create":
			out, err := r.client.CreateTrustPolicy(r.ctx, obj)
			if err != nil {
				err = ignoreExpectedErrors(r.Mode, obj.GetKey(), err)
				r.logErr(fmt.Sprintf("TrustPolicyApi[%d]", ii), err)
			} else {
				outp, ok := dataOut.(*[][]edgeproto.Result)
				if !ok {
					panic(fmt.Sprintf("RunTrustPolicyApi expected dataOut type *[][]edgeproto.Result, but was %T", dataOut))
				}
				*outp = append(*outp, out)
			}
		case "delete":
			out, err := r.client.DeleteTrustPolicy(r.ctx, obj)
			if err != nil {
				err = ignoreExpectedErrors(r.Mode, obj.GetKey(), err)
				r.logErr(fmt.Sprintf("TrustPolicyApi[%d]", ii), err)
			} else {
				outp, ok := dataOut.(*[][]edgeproto.Result)
				if !ok {
					panic(fmt.Sprintf("RunTrustPolicyApi expected dataOut type *[][]edgeproto.Result, but was %T", dataOut))
				}
				*outp = append(*outp, out)
			}
		case "update":
			// set specified fields
			objMap, err := cli.GetGenericObjFromList(dataMap, ii)
			if err != nil {
				log.DebugLog(log.DebugLevelApi, "bad dataMap for TrustPolicy", "err", err)
				*r.Rc = false
				return
			}
			yamlData := cli.MapData{
				Namespace: cli.YamlNamespace,
				Data:      objMap,
			}
			obj.Fields = cli.GetSpecifiedFields(&yamlData, obj)

			out, err := r.client.UpdateTrustPolicy(r.ctx, obj)
			if err != nil {
				err = ignoreExpectedErrors(r.Mode, obj.GetKey(), err)
				r.logErr(fmt.Sprintf("TrustPolicyApi[%d]", ii), err)
			} else {
				outp, ok := dataOut.(*[][]edgeproto.Result)
				if !ok {
					panic(fmt.Sprintf("RunTrustPolicyApi expected dataOut type *[][]edgeproto.Result, but was %T", dataOut))
				}
				*outp = append(*outp, out)
			}
		case "showfiltered":
			out, err := r.client.ShowTrustPolicy(r.ctx, obj)
			if err != nil {
				r.logErr(fmt.Sprintf("TrustPolicyApi[%d]", ii), err)
			} else {
				outp, ok := dataOut.(*[]edgeproto.TrustPolicy)
				if !ok {
					panic(fmt.Sprintf("RunTrustPolicyApi expected dataOut type *[]edgeproto.TrustPolicy, but was %T", dataOut))
				}
				*outp = append(*outp, out...)
			}
		}
	}
}

func (s *DummyServer) CreateTrustPolicy(in *edgeproto.TrustPolicy, server edgeproto.TrustPolicyApi_CreateTrustPolicyServer) error {
	var err error
	if true {
		for ii := 0; ii < s.ShowDummyCount; ii++ {
			server.Send(&edgeproto.Result{Message: "some message"})
		}
		if ch, ok := s.MidstreamFailChs["CreateTrustPolicy"]; ok {
			// Wait until client receives the SendMsg, since they
			// are buffered and dropped once we return err here.
			select {
			case <-ch:
			case <-time.After(5 * time.Second):
			}
			return fmt.Errorf("midstream failure!")
		}
	}
	s.TrustPolicyCache.Update(server.Context(), in, 0)
	return err
}

func (s *DummyServer) DeleteTrustPolicy(in *edgeproto.TrustPolicy, server edgeproto.TrustPolicyApi_DeleteTrustPolicyServer) error {
	var err error
	if true {
		for ii := 0; ii < s.ShowDummyCount; ii++ {
			server.Send(&edgeproto.Result{Message: "some message"})
		}
		if ch, ok := s.MidstreamFailChs["DeleteTrustPolicy"]; ok {
			// Wait until client receives the SendMsg, since they
			// are buffered and dropped once we return err here.
			select {
			case <-ch:
			case <-time.After(5 * time.Second):
			}
			return fmt.Errorf("midstream failure!")
		}
	}
	s.TrustPolicyCache.Delete(server.Context(), in, 0)
	return err
}

func (s *DummyServer) UpdateTrustPolicy(in *edgeproto.TrustPolicy, server edgeproto.TrustPolicyApi_UpdateTrustPolicyServer) error {
	var err error
	if true {
		for ii := 0; ii < s.ShowDummyCount; ii++ {
			server.Send(&edgeproto.Result{Message: "some message"})
		}
		if ch, ok := s.MidstreamFailChs["UpdateTrustPolicy"]; ok {
			// Wait until client receives the SendMsg, since they
			// are buffered and dropped once we return err here.
			select {
			case <-ch:
			case <-time.After(5 * time.Second):
			}
			return fmt.Errorf("midstream failure!")
		}
	}
	s.TrustPolicyCache.Update(server.Context(), in, 0)
	return err
}

func (s *DummyServer) ShowTrustPolicy(in *edgeproto.TrustPolicy, server edgeproto.TrustPolicyApi_ShowTrustPolicyServer) error {
	var err error
	obj := &edgeproto.TrustPolicy{}
	if obj.Matches(in, edgeproto.MatchFilter()) {
		for ii := 0; ii < s.ShowDummyCount; ii++ {
			server.Send(&edgeproto.TrustPolicy{})
		}
		if ch, ok := s.MidstreamFailChs["ShowTrustPolicy"]; ok {
			// Wait until client receives the SendMsg, since they
			// are buffered and dropped once we return err here.
			select {
			case <-ch:
			case <-time.After(5 * time.Second):
			}
			return fmt.Errorf("midstream failure!")
		}
	}
	err = s.TrustPolicyCache.Show(in, func(obj *edgeproto.TrustPolicy) error {
		err := server.Send(obj)
		return err
	})
	return err
}

type ResultStream interface {
	Recv() (*edgeproto.Result, error)
}

func ResultReadStream(stream ResultStream) ([]edgeproto.Result, error) {
	output := []edgeproto.Result{}
	for {
		obj, err := stream.Recv()
		if err == io.EOF {
			break
		}
		if err != nil {
			return output, fmt.Errorf("read Result stream failed, %v", err)
		}
		output = append(output, *obj)
	}
	return output, nil
}

func (s *ApiClient) CreateTrustPolicy(ctx context.Context, in *edgeproto.TrustPolicy) ([]edgeproto.Result, error) {
	api := edgeproto.NewTrustPolicyApiClient(s.Conn)
	stream, err := api.CreateTrustPolicy(ctx, in)
	if err != nil {
		return nil, err
	}
	return ResultReadStream(stream)
}

func (s *CliClient) CreateTrustPolicy(ctx context.Context, in *edgeproto.TrustPolicy) ([]edgeproto.Result, error) {
	output := []edgeproto.Result{}
	args := append(s.BaseArgs, "controller", "CreateTrustPolicy")
	err := wrapper.RunEdgectlObjs(args, in, &output, s.RunOps...)
	return output, err
}

func (s *ApiClient) DeleteTrustPolicy(ctx context.Context, in *edgeproto.TrustPolicy) ([]edgeproto.Result, error) {
	api := edgeproto.NewTrustPolicyApiClient(s.Conn)
	stream, err := api.DeleteTrustPolicy(ctx, in)
	if err != nil {
		return nil, err
	}
	return ResultReadStream(stream)
}

func (s *CliClient) DeleteTrustPolicy(ctx context.Context, in *edgeproto.TrustPolicy) ([]edgeproto.Result, error) {
	output := []edgeproto.Result{}
	args := append(s.BaseArgs, "controller", "DeleteTrustPolicy")
	err := wrapper.RunEdgectlObjs(args, in, &output, s.RunOps...)
	return output, err
}

func (s *ApiClient) UpdateTrustPolicy(ctx context.Context, in *edgeproto.TrustPolicy) ([]edgeproto.Result, error) {
	api := edgeproto.NewTrustPolicyApiClient(s.Conn)
	stream, err := api.UpdateTrustPolicy(ctx, in)
	if err != nil {
		return nil, err
	}
	return ResultReadStream(stream)
}

func (s *CliClient) UpdateTrustPolicy(ctx context.Context, in *edgeproto.TrustPolicy) ([]edgeproto.Result, error) {
	output := []edgeproto.Result{}
	args := append(s.BaseArgs, "controller", "UpdateTrustPolicy")
	err := wrapper.RunEdgectlObjs(args, in, &output, s.RunOps...)
	return output, err
}

type TrustPolicyStream interface {
	Recv() (*edgeproto.TrustPolicy, error)
}

func TrustPolicyReadStream(stream TrustPolicyStream) ([]edgeproto.TrustPolicy, error) {
	output := []edgeproto.TrustPolicy{}
	for {
		obj, err := stream.Recv()
		if err == io.EOF {
			break
		}
		if err != nil {
			return output, fmt.Errorf("read TrustPolicy stream failed, %v", err)
		}
		output = append(output, *obj)
	}
	return output, nil
}

func (s *ApiClient) ShowTrustPolicy(ctx context.Context, in *edgeproto.TrustPolicy) ([]edgeproto.TrustPolicy, error) {
	api := edgeproto.NewTrustPolicyApiClient(s.Conn)
	stream, err := api.ShowTrustPolicy(ctx, in)
	if err != nil {
		return nil, err
	}
	return TrustPolicyReadStream(stream)
}

func (s *CliClient) ShowTrustPolicy(ctx context.Context, in *edgeproto.TrustPolicy) ([]edgeproto.TrustPolicy, error) {
	output := []edgeproto.TrustPolicy{}
	args := append(s.BaseArgs, "controller", "ShowTrustPolicy")
	err := wrapper.RunEdgectlObjs(args, in, &output, s.RunOps...)
	return output, err
}

type TrustPolicyApiClient interface {
	CreateTrustPolicy(ctx context.Context, in *edgeproto.TrustPolicy) ([]edgeproto.Result, error)
	DeleteTrustPolicy(ctx context.Context, in *edgeproto.TrustPolicy) ([]edgeproto.Result, error)
	UpdateTrustPolicy(ctx context.Context, in *edgeproto.TrustPolicy) ([]edgeproto.Result, error)
	ShowTrustPolicy(ctx context.Context, in *edgeproto.TrustPolicy) ([]edgeproto.TrustPolicy, error)
}
