# Copyright 2024 EdgeXR, Inc
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

---
- name: Set vars for notify endpoint
  # it is assumed the address does not have a http:// scheme
  ansible.builtin.set_fact:
    controller_notify_host: "{{ controller_notify_parts[0] }}"
    controller_notify_port: "{{ contorller_notify_parts[1] | default(443) }}"
  vars:
    controller_notify_parts: "{{ notifyAddrs.split(':') }}"

- name: Wait for controller's notify port to be reachable
  wait_for:
    host: "{{ controller_notify_host }}"
    port: "{{ controller_notify_port }}"
    timeout: 10
