// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: cloudletpool.proto

package notify

import (
	"context"
	fmt "fmt"
	_ "github.com/edgexr/edge-cloud-platform/api/dme-proto"
	edgeproto "github.com/edgexr/edge-cloud-platform/api/edgeproto"
	"github.com/edgexr/edge-cloud-platform/pkg/log"
	_ "github.com/edgexr/edge-cloud-platform/tools/protogen"
	_ "github.com/gogo/googleapis/google/api"
	_ "github.com/gogo/protobuf/gogoproto"
	proto "github.com/gogo/protobuf/proto"
	"github.com/gogo/protobuf/types"
	opentracing "github.com/opentracing/opentracing-go"
	math "math"
	"sync"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// Auto-generated code: DO NOT EDIT

type SendCloudletPoolHandler interface {
	GetAllKeys(ctx context.Context, cb func(key *edgeproto.CloudletPoolKey, modRev int64))
	GetWithRev(key *edgeproto.CloudletPoolKey, buf *edgeproto.CloudletPool, modRev *int64) bool
}

type RecvCloudletPoolHandler interface {
	Update(ctx context.Context, in *edgeproto.CloudletPool, rev int64)
	Delete(ctx context.Context, in *edgeproto.CloudletPool, rev int64)
	Prune(ctx context.Context, keys map[edgeproto.CloudletPoolKey]struct{})
	Flush(ctx context.Context, notifyId int64)
}

type CloudletPoolCacheHandler interface {
	SendCloudletPoolHandler
	RecvCloudletPoolHandler
	AddNotifyCb(fn func(ctx context.Context, obj *edgeproto.CloudletPoolKey, old *edgeproto.CloudletPool, modRev int64))
}

type CloudletPoolSend struct {
	Name        string
	MessageName string
	handler     SendCloudletPoolHandler
	Keys        map[edgeproto.CloudletPoolKey]CloudletPoolSendContext
	keysToSend  map[edgeproto.CloudletPoolKey]CloudletPoolSendContext
	notifyId    int64
	Mux         sync.Mutex
	buf         edgeproto.CloudletPool
	SendCount   uint64
	sendrecv    *SendRecv
}

type CloudletPoolSendContext struct {
	ctx         context.Context
	modRev      int64
	forceDelete bool
}

func NewCloudletPoolSend(handler SendCloudletPoolHandler) *CloudletPoolSend {
	send := &CloudletPoolSend{}
	send.Name = "CloudletPool"
	send.MessageName = proto.MessageName((*edgeproto.CloudletPool)(nil))
	send.handler = handler
	send.Keys = make(map[edgeproto.CloudletPoolKey]CloudletPoolSendContext)
	return send
}

func (s *CloudletPoolSend) SetSendRecv(sendrecv *SendRecv) {
	s.sendrecv = sendrecv
}

func (s *CloudletPoolSend) GetMessageName() string {
	return s.MessageName
}

func (s *CloudletPoolSend) GetName() string {
	return s.Name
}

func (s *CloudletPoolSend) GetSendCount() uint64 {
	return s.SendCount
}

func (s *CloudletPoolSend) GetNotifyId() int64 {
	return s.notifyId
}
func (s *CloudletPoolSend) UpdateAll(ctx context.Context) {
	if !s.sendrecv.isRemoteWanted(s.MessageName) {
		return
	}
	s.Mux.Lock()
	s.handler.GetAllKeys(ctx, func(key *edgeproto.CloudletPoolKey, modRev int64) {
		s.Keys[*key] = CloudletPoolSendContext{
			ctx:    ctx,
			modRev: modRev,
		}
	})
	s.Mux.Unlock()
}

func (s *CloudletPoolSend) Update(ctx context.Context, key *edgeproto.CloudletPoolKey, old *edgeproto.CloudletPool, modRev int64) {
	if !s.sendrecv.isRemoteWanted(s.MessageName) {
		return
	}
	forceDelete := false
	s.updateInternal(ctx, key, modRev, forceDelete)
}

func (s *CloudletPoolSend) ForceDelete(ctx context.Context, key *edgeproto.CloudletPoolKey, modRev int64) {
	forceDelete := true
	s.updateInternal(ctx, key, modRev, forceDelete)
}

func (s *CloudletPoolSend) updateInternal(ctx context.Context, key *edgeproto.CloudletPoolKey, modRev int64, forceDelete bool) {
	s.Mux.Lock()
	log.SpanLog(ctx, log.DebugLevelNotify, "updateInternal CloudletPool", "key", key, "modRev", modRev)
	s.Keys[*key] = CloudletPoolSendContext{
		ctx:         ctx,
		modRev:      modRev,
		forceDelete: forceDelete,
	}
	s.Mux.Unlock()
	s.sendrecv.wakeup()
}

func (s *CloudletPoolSend) SendForCloudlet(ctx context.Context, action edgeproto.NoticeAction, cloudlet *edgeproto.Cloudlet) {
}

func (s *CloudletPoolSend) Send(stream StreamNotify, notice *edgeproto.Notice, peer string) error {
	s.Mux.Lock()
	keys := s.keysToSend
	s.keysToSend = nil
	s.Mux.Unlock()
	for key, sendContext := range keys {
		ctx := sendContext.ctx
		found := s.handler.GetWithRev(&key, &s.buf, &notice.ModRev)
		if found && !sendContext.forceDelete {
			notice.Action = edgeproto.NoticeAction_UPDATE
		} else {
			notice.Action = edgeproto.NoticeAction_DELETE
			notice.ModRev = sendContext.modRev
			s.buf.Reset()
			s.buf.SetKey(&key)
		}
		any, err := types.MarshalAny(&s.buf)
		if err != nil {
			s.sendrecv.stats.MarshalErrors++
			err = nil
			continue
		}
		notice.Any = *any
		notice.Span = log.SpanToString(ctx)
		log.SpanLog(ctx, log.DebugLevelNotify,
			fmt.Sprintf("%s send CloudletPool", s.sendrecv.cliserv),
			"peerAddr", peer,
			"peer", s.sendrecv.peer,
			"local", s.sendrecv.name,
			"action", notice.Action,
			"key", key,
			"modRev", notice.ModRev)
		err = stream.Send(notice)
		if err != nil {
			s.sendrecv.stats.SendErrors++
			return err
		}
		s.sendrecv.stats.Send++
		// object specific counter
		s.SendCount++
	}
	return nil
}

func (s *CloudletPoolSend) PrepData() bool {
	s.Mux.Lock()
	defer s.Mux.Unlock()
	if len(s.Keys) > 0 {
		s.keysToSend = s.Keys
		s.Keys = make(map[edgeproto.CloudletPoolKey]CloudletPoolSendContext)
		return true
	}
	return false
}

// Server accepts multiple clients so needs to track multiple
// peers to send to.
type CloudletPoolSendMany struct {
	handler SendCloudletPoolHandler
	Mux     sync.Mutex
	sends   map[string]*CloudletPoolSend
}

func NewCloudletPoolSendMany(handler SendCloudletPoolHandler) *CloudletPoolSendMany {
	s := &CloudletPoolSendMany{}
	s.handler = handler
	s.sends = make(map[string]*CloudletPoolSend)
	return s
}

func (s *CloudletPoolSendMany) NewSend(peerAddr string, notifyId int64) NotifySend {
	send := NewCloudletPoolSend(s.handler)
	send.notifyId = notifyId
	s.Mux.Lock()
	s.sends[peerAddr] = send
	s.Mux.Unlock()
	return send
}

func (s *CloudletPoolSendMany) DoneSend(peerAddr string, send NotifySend) {
	asend, ok := send.(*CloudletPoolSend)
	if !ok {
		return
	}
	// another connection may come from the same client so remove
	// only if it matches
	s.Mux.Lock()
	if remove, _ := s.sends[peerAddr]; remove == asend {
		delete(s.sends, peerAddr)
	}
	s.Mux.Unlock()
}
func (s *CloudletPoolSendMany) Update(ctx context.Context, key *edgeproto.CloudletPoolKey, old *edgeproto.CloudletPool, modRev int64) {
	s.Mux.Lock()
	defer s.Mux.Unlock()
	for _, send := range s.sends {
		send.Update(ctx, key, old, modRev)
	}
}

func (s *CloudletPoolSendMany) GetTypeString() string {
	return "CloudletPool"
}

type CloudletPoolRecv struct {
	Name        string
	MessageName string
	handler     RecvCloudletPoolHandler
	sendAllKeys map[edgeproto.CloudletPoolKey]struct{}
	Mux         sync.Mutex
	buf         edgeproto.CloudletPool
	RecvCount   uint64
	sendrecv    *SendRecv
}

func NewCloudletPoolRecv(handler RecvCloudletPoolHandler) *CloudletPoolRecv {
	recv := &CloudletPoolRecv{}
	recv.Name = "CloudletPool"
	recv.MessageName = proto.MessageName((*edgeproto.CloudletPool)(nil))
	recv.handler = handler
	return recv
}

func (s *CloudletPoolRecv) SetSendRecv(sendrecv *SendRecv) {
	s.sendrecv = sendrecv
}

func (s *CloudletPoolRecv) GetMessageName() string {
	return s.MessageName
}

func (s *CloudletPoolRecv) GetName() string {
	return s.Name
}

func (s *CloudletPoolRecv) GetRecvCount() uint64 {
	return s.RecvCount
}

func (s *CloudletPoolRecv) Recv(ctx context.Context, notice *edgeproto.Notice, notifyId int64, peerAddr string) {
	span := opentracing.SpanFromContext(ctx)
	if span != nil {
		span.SetTag("objtype", "CloudletPool")
	}

	buf := &edgeproto.CloudletPool{}
	err := types.UnmarshalAny(&notice.Any, buf)
	if err != nil {
		s.sendrecv.stats.UnmarshalErrors++
		log.SpanLog(ctx, log.DebugLevelNotify, "Unmarshal Error", "err", err)
		return
	}
	if span != nil {
		log.SetTags(span, buf.GetKey().GetTags())
	}
	log.SpanLog(ctx, log.DebugLevelNotify,
		fmt.Sprintf("%s recv CloudletPool", s.sendrecv.cliserv),
		"peerAddr", peerAddr,
		"peer", s.sendrecv.peer,
		"local", s.sendrecv.name,
		"action", notice.Action,
		"key", buf.GetKeyVal(),
		"modRev", notice.ModRev)
	if notice.Action == edgeproto.NoticeAction_UPDATE {
		s.handler.Update(ctx, buf, notice.ModRev)
		s.Mux.Lock()
		if s.sendAllKeys != nil {
			s.sendAllKeys[buf.GetKeyVal()] = struct{}{}
		}
		s.Mux.Unlock()
	} else if notice.Action == edgeproto.NoticeAction_DELETE {
		s.handler.Delete(ctx, buf, notice.ModRev)
	}
	s.sendrecv.stats.Recv++
	// object specific counter
	s.RecvCount++
}

func (s *CloudletPoolRecv) RecvAllStart() {
	s.Mux.Lock()
	defer s.Mux.Unlock()
	s.sendAllKeys = make(map[edgeproto.CloudletPoolKey]struct{})
}

func (s *CloudletPoolRecv) RecvAllEnd(ctx context.Context, cleanup Cleanup) {
	s.Mux.Lock()
	validKeys := s.sendAllKeys
	s.sendAllKeys = nil
	s.Mux.Unlock()
	if cleanup == CleanupPrune {
		s.handler.Prune(ctx, validKeys)
	}
}
func (s *CloudletPoolRecv) Flush(ctx context.Context, notifyId int64) {
	s.handler.Flush(ctx, notifyId)
}

type CloudletPoolRecvMany struct {
	handler RecvCloudletPoolHandler
}

func NewCloudletPoolRecvMany(handler RecvCloudletPoolHandler) *CloudletPoolRecvMany {
	s := &CloudletPoolRecvMany{}
	s.handler = handler
	return s
}

func (s *CloudletPoolRecvMany) NewRecv() NotifyRecv {
	recv := NewCloudletPoolRecv(s.handler)
	return recv
}

func (s *CloudletPoolRecvMany) Flush(ctx context.Context, notifyId int64) {
	s.handler.Flush(ctx, notifyId)
}
func (mgr *ServerMgr) RegisterSendCloudletPoolCache(cache CloudletPoolCacheHandler) {
	send := NewCloudletPoolSendMany(cache)
	mgr.RegisterSend(send)
	cache.AddNotifyCb(send.Update)
}

func (mgr *ServerMgr) RegisterRecvCloudletPoolCache(cache CloudletPoolCacheHandler) {
	recv := NewCloudletPoolRecvMany(cache)
	mgr.RegisterRecv(recv)
}

func (s *Client) RegisterSendCloudletPoolCache(cache CloudletPoolCacheHandler) {
	send := NewCloudletPoolSend(cache)
	s.RegisterSend(send)
	cache.AddNotifyCb(send.Update)
}

func (s *Client) RegisterRecvCloudletPoolCache(cache CloudletPoolCacheHandler) {
	recv := NewCloudletPoolRecv(cache)
	s.RegisterRecv(recv)
}
