network:
  version: 2
  ethernets:
    ens3:
      addresses:
      - 10.101.0.2/16
      - fc00:101:ecec::2/64
      nameservers:
        addresses:
        - 1.1.1.1
        - 8.8.8.8
        - 2606:4700:4700::1111
        - 2001:4860:4860::8888
      routes:
      - to: 0.0.0.0/0
        via: 10.101.0.1
      - to: ::/0
        via: fc00:101:ecec::1
