// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: version.proto

package controller

import (
	fmt "fmt"
	_ "github.com/edgexr/edge-cloud-platform/tools/protogen"
	_ "github.com/gogo/protobuf/gogoproto"
	proto "github.com/gogo/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

type VersionUpgrade struct {
	id          int32
	hash        string
	upgradeFunc VersionUpgradeFunc
	name        string
}

var VersionHash_UpgradeFuncs = []VersionUpgrade{
	{0, "d41d8cd98f00b204e9800998ecf8427e", nil, ""},
	{52, "c2d882033b0c14f28cece41cf4010060", nil, ""},
	{53, "14ae4c721c1bace6e8379d0061a72a77", UpgradeCrmOnEdge, "UpgradeCrmOnEdge"},
	{54, "eff9d3a6c74fd02840efce05d1984e8d", AddStaticFqdn, "AddStaticFqdn"},
	{55, "eac56710c013d954db31eeb306b514a4", InstanceKeysRegionScopedName, "InstanceKeysRegionScopedName"},
}

// Auto-generated code: DO NOT EDIT
